-- MySQL Script generated by MySQL Workbench
-- Mon Jul 21 22:48:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seguimiento_entregas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguimiento_entregas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_pedidos` ;

-- -----------------------------------------------------
-- Table `sistema_pedidos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `cuit` VARCHAR(255) NOT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `habilitado` TINYINT(1) NULL DEFAULT '1',
  `fecha_proximo_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`rol` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rol_type` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `rol_id` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `sistema_pedidos`.`rol` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_pedido` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `seguimiento_dist` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NULL DEFAULT 'pendiente',
  `fecha_proximo_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_pedidos`.`clientes` (`id_cliente`),
  CONSTRAINT `pedidos_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_pedidos`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  `id_proveedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `sistema_pedidos`.`proveedores` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`detalle_pedido` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_pedido_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `sistema_pedidos`.`pedidos` (`id_pedido`),
  CONSTRAINT `detalle_pedido_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sistema_pedidos`.`productos` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`pedido_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`pedido_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `id_cliente` INT NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `usado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token` (`token` ASC) VISIBLE,
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `pedido_tokens_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_pedidos`.`clientes` (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_pedidos`.`productos_habilitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedidos`.`productos_habilitados` (
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `productos_habilitados_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_pedidos`.`clientes` (`id_cliente`),
  CONSTRAINT `productos_habilitados_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sistema_pedidos`.`productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `seguimiento_entregas` ;

-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `cuit` VARCHAR(20) NULL DEFAULT NULL,
  `domicilio` VARCHAR(255) NULL DEFAULT NULL,
  `localidad` VARCHAR(100) NULL DEFAULT NULL,
  `condicion_iva` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cuit` (`cuit` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`remitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`remitos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_remito` VARCHAR(50) NOT NULL,
  `cliente_id` INT NOT NULL,
  `fecha_emision` DATE NULL DEFAULT NULL,
  `condicion_operacion` VARCHAR(100) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `archivo_pdf` VARCHAR(255) NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'entregado', 'parcial') NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_remito` (`numero_remito` ASC) VISIBLE,
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `remitos_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `seguimiento_entregas`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `rol` ENUM('admin', 'operario') NULL DEFAULT 'operario',
  `creado_en` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`entregas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remito_id` INT NOT NULL,
  `operario_id` INT NOT NULL,
  `fecha_entrega` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre_operario` VARCHAR(100) NULL DEFAULT NULL,
  `entrega_parcial` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indica si la entrega fue parcial (1) o completa (0)',
  PRIMARY KEY (`id`),
  INDEX `remito_id` (`remito_id` ASC) VISIBLE,
  INDEX `operario_id` (`operario_id` ASC) VISIBLE,
  CONSTRAINT `entregas_ibfk_1`
    FOREIGN KEY (`remito_id`)
    REFERENCES `seguimiento_entregas`.`remitos` (`id`),
  CONSTRAINT `entregas_ibfk_2`
    FOREIGN KEY (`operario_id`)
    REFERENCES `seguimiento_entregas`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_bit` VARCHAR(20) NULL DEFAULT NULL,
  `codigo_barra` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `unidad_medida` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_bit` (`codigo_bit` ASC) VISIBLE,
  UNIQUE INDEX `codigo_barra` (`codigo_barra` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`entrega_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`entrega_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entrega_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `codigo_barra` VARCHAR(50) NOT NULL,
  `fecha_escaneo` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `entrega_id` (`entrega_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `entrega_detalle_ibfk_1`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `seguimiento_entregas`.`entregas` (`id`),
  CONSTRAINT `entrega_detalle_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `seguimiento_entregas`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`remito_operarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`remito_operarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remito_id` INT NOT NULL,
  `operario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `remito_id` (`remito_id` ASC) VISIBLE,
  INDEX `operario_id` (`operario_id` ASC) VISIBLE,
  CONSTRAINT `remito_operarios_ibfk_1`
    FOREIGN KEY (`remito_id`)
    REFERENCES `seguimiento_entregas`.`remitos` (`id`),
  CONSTRAINT `remito_operarios_ibfk_2`
    FOREIGN KEY (`operario_id`)
    REFERENCES `seguimiento_entregas`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`remito_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`remito_productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remito_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `entregado` TINYINT(1) NULL DEFAULT '0',
  `cantidad_entregada` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `remito_id` (`remito_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `remito_productos_ibfk_1`
    FOREIGN KEY (`remito_id`)
    REFERENCES `seguimiento_entregas`.`remitos` (`id`),
  CONSTRAINT `remito_productos_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `seguimiento_entregas`.`productos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_entregas`.`tokens_acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_entregas`.`tokens_acceso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remito_id` INT NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `expiracion` DATETIME NULL DEFAULT NULL,
  `usado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token` (`token` ASC) VISIBLE,
  INDEX `remito_id` (`remito_id` ASC) VISIBLE,
  CONSTRAINT `tokens_acceso_ibfk_1`
    FOREIGN KEY (`remito_id`)
    REFERENCES `seguimiento_entregas`.`remitos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
